name: CI

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}

    services:
      neo4j:
        image: neo4j:5.19
        env:
          NEO4J_AUTH: "neo4j/test-password"
        ports:
          - 7688:7687
        options: --health-cmd "cypher-shell -u neo4j -p test-password 'RETURN 1'" --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        python-version: [ 3.12 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v9

      - name: Install dependencies
        run: poetry install

      - name: Create .env file
        run: |
          echo "NEO4J_USER=neo4j" > .env
          echo "NEO4J_PASSWORD=test-password" >> .env
          echo "DATABASE_URL=bolt://neo4j:test-password@localhost:7688" >> .env

      - name: Run pre-commit hooks
        run: poetry run pre-commit run --all-files --show-diff-on-failure
